import { describe, expect, it } from "vitest"
import { assertSafe, assertUnsafe } from "../helpers/assertions"

describe("addColumnDefault", () => {
    /**
     * Postgres 11+ and MySQL 8.0.12+ both write a fast default, so the only case
     * that still rewrites the table is a uuid column defaulted to a volatile
     * function. Generalizing this would flag `DEFAULT now()` on every timestamp
     * column — safe, ubiquitous, and something the gem deliberately allows too.
     */
    it("flags a uuid column with a volatile function default", async () => {
        const error = await assertUnsafe(
            (qr) =>
                qr.query(
                    `ALTER TABLE "users" ADD "public_id" uuid NOT NULL DEFAULT gen_random_uuid()`,
                ),
            /volatile default blocks reads and writes/,
            { volatileFunctions: { gen_random_uuid: true } },
        )
        expect(error.key).toBe("addColumnDefault")
        expect(error.message).toContain("SET DEFAULT gen_random_uuid()")
    })

    it("allows a uuid column whose default function is stable", async () => {
        await assertSafe(
            (qr) =>
                qr.query(
                    `ALTER TABLE "users" ADD "public_id" uuid DEFAULT stable_uuid()`,
                ),
            { volatileFunctions: { stable_uuid: false } },
        )
    })

    it("allows a constant default", async () => {
        await assertSafe((qr) =>
            qr.query(`ALTER TABLE "users" ADD "n" integer DEFAULT 0`),
        )
    })

    it("allows now() on a timestamp column", async () => {
        await assertSafe((qr) =>
            qr.query(
                `ALTER TABLE "users" ADD "created_at" TIMESTAMP DEFAULT now()`,
            ),
        )
    })

    it("allows any default on a table created in the same migration", async () => {
        await assertSafe(
            async (qr) => {
                await qr.query(`CREATE TABLE "fresh" ("id" SERIAL NOT NULL)`)
                await qr.query(
                    `ALTER TABLE "fresh" ADD "u" uuid DEFAULT gen_random_uuid()`,
                )
            },
            { volatileFunctions: { gen_random_uuid: true } },
        )
    })
})

describe("addColumnJson", () => {
    it("suggests jsonb on Postgres", async () => {
        const error = await assertUnsafe(
            (qr) => qr.query(`ALTER TABLE "users" ADD "payload" json`),
            /Use jsonb instead/,
        )
        expect(error.message).toContain("jsonb")
    })

    it("does not apply to MySQL, which has no jsonb", async () => {
        await assertSafe(
            (qr) => qr.query("ALTER TABLE `users` ADD `payload` json"),
            {
                dialect: "mysql",
            },
        )
    })
})

describe("addColumnGeneratedStored", () => {
    it("flags a stored generated column", async () => {
        await assertUnsafe(
            (qr) =>
                qr.query(
                    `ALTER TABLE "users" ADD "total" integer GENERATED ALWAYS AS (a + b) STORED`,
                ),
            /stored generated column/,
        )
    })

    it("allows a virtual generated column", async () => {
        await assertSafe((qr) =>
            qr.query(
                `ALTER TABLE "users" ADD "total" integer GENERATED ALWAYS AS (a + b) VIRTUAL`,
            ),
        )
    })
})

describe("addColumnAutoIncrementing", () => {
    it("flags SERIAL on Postgres", async () => {
        await assertUnsafe(
            (qr) => qr.query(`ALTER TABLE "users" ADD "seq" SERIAL NOT NULL`),
            /auto-incrementing column/,
        )
    })

    it("flags GENERATED AS IDENTITY", async () => {
        await assertUnsafe(
            (qr) =>
                qr.query(
                    `ALTER TABLE "users" ADD "seq" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
                ),
            /auto-incrementing column/,
        )
    })

    it("flags AUTO_INCREMENT on MySQL and mentions replication", async () => {
        const error = await assertUnsafe(
            (qr) =>
                qr.query("ALTER TABLE `users` ADD `seq` int AUTO_INCREMENT"),
            /auto-incrementing column/,
            { dialect: "mysql" },
        )
        expect(error.message).toContain("statement-based replication")
    })

    it("allows a plain integer column", async () => {
        await assertSafe((qr) =>
            qr.query(`ALTER TABLE "users" ADD "n" integer`),
        )
    })
})

describe("addColumnDefaultExpression", () => {
    it("flags a JavaScript function passed as a default", async () => {
        await assertUnsafe(
            (qr) =>
                qr.addColumn("users", {
                    name: "created_at",
                    type: "timestamp",
                    default: () => "now()",
                } as never),
            /cannot determine whether the default expression/,
        )
    })
})
