import { describe, expect, it } from "vitest"
import { analyzeSql } from "../../src/sql/analyze"
import type { Dialect, Operation } from "../../src/operations/types"

/**
 * The acceptance target: everything `typeorm migration:generate` emits must parse.
 *
 * These are the rendered forms of the template literals in
 * `PostgresQueryRunner.ts` and `MysqlQueryRunner.ts`, quirks included — the double
 * space and trailing space in `createIndexSql`, `ADD` without `COLUMN` on Postgres,
 * `CHANGE` rather than `MODIFY` on MySQL, `numeric(12,7) array`, and the
 * semicolon-joined `CREATE TABLE` + `COMMENT ON COLUMN` that arrives as a single
 * `query()` call.
 *
 * A single `kind: "unknown"` here means a real-world generated migration would go
 * unchecked, so that is what the sweep asserts.
 */

export const POSTGRES_CORPUS: string[] = [
    // tables
    `CREATE TABLE "post" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_be5f" PRIMARY KEY ("id"))`,
    `CREATE TABLE "foo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bar" numeric(12,7) array NOT NULL, CONSTRAINT "PK_foo" PRIMARY KEY ("id"))`,
    `CREATE TABLE "user" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT "PK_cace" PRIMARY KEY ("id"))`,
    `CREATE TABLE "public"."scoped" ("id" SERIAL NOT NULL)`,
    // TypeORM joins the comment onto the CREATE with a semicolon, in one query() call
    `CREATE TABLE "post" ("id" SERIAL NOT NULL); COMMENT ON COLUMN "post"."id" IS 'the id'`,
    `DROP TABLE "post"`,
    `ALTER TABLE "post" RENAME TO "article"`,

    // columns — note Postgres emits ADD, not ADD COLUMN
    `ALTER TABLE "entity_with_virtual_column" ADD "foo" integer NOT NULL`,
    `ALTER TABLE "users" ADD "uuid" uuid NOT NULL DEFAULT gen_random_uuid()`,
    `ALTER TABLE "users" ADD "payload" json`,
    `ALTER TABLE "users" ADD "total" integer GENERATED ALWAYS AS (a + b) STORED`,
    `ALTER TABLE "users" ADD "seq" SERIAL NOT NULL`,
    `ALTER TABLE "post" DROP COLUMN "title"`,
    `ALTER TABLE "post" RENAME COLUMN "title" TO "name"`,
    `ALTER TABLE "post" ALTER COLUMN "title" TYPE character varying(500)`,
    `ALTER TABLE "post" ALTER COLUMN "title" SET NOT NULL`,
    `ALTER TABLE "post" ALTER COLUMN "title" DROP NOT NULL`,
    `ALTER TABLE "post" ALTER COLUMN "title" SET DEFAULT 'x'`,
    `ALTER TABLE "post" ALTER COLUMN "title" DROP DEFAULT`,
    `ALTER TABLE "post" ALTER COLUMN "id" SET DEFAULT nextval('"post_id_seq"')`,
    `ALTER TABLE "foo" ALTER COLUMN "bar" TYPE "public"."foo_bar_enum_old" USING "bar"::"text"::"public"."foo_bar_enum_old"`,
    `COMMENT ON COLUMN "post"."title" IS NULL`,

    // indexes — the double space and trailing space are what TypeORM actually emits
    `CREATE INDEX "IDX_a" ON "post"  ("title") `,
    `CREATE UNIQUE INDEX "IDX_b" ON "post"  ("title") `,
    `CREATE INDEX CONCURRENTLY "IDX_c" ON "post"  ("title") `,
    `CREATE INDEX "IDX_d" ON "public"."post" USING gin ("body") WHERE deleted_at IS NULL`,
    `DROP INDEX "public"."IDX_a"`,
    `DROP INDEX CONCURRENTLY "IDX_a"`,

    // constraints — note no space before ( on REFERENCES
    `ALTER TABLE "account" ADD CONSTRAINT "FK_6032" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    `ALTER TABLE "post" ADD CONSTRAINT "UQ_1" UNIQUE ("title")`,
    `ALTER TABLE "example_entity" ADD CONSTRAINT "CHK_0528_ENUM" CHECK (enumcolumn IN ('enumvalue1','enumvalue2','enumvalue3'))`,
    `ALTER TABLE "room" ADD CONSTRAINT "EX_1" EXCLUDE USING gist (during WITH &&)`,
    `ALTER TABLE "post" ADD CONSTRAINT "PK_1" PRIMARY KEY ("id")`,
    `ALTER TABLE "post" DROP CONSTRAINT "FK_6032"`,

    // enums
    `ALTER TYPE "public"."foo_with_special_chars_bar_enum" ADD VALUE 'say ''hello'' there'`,
    `ALTER TYPE "public"."status_enum" RENAME VALUE 'old' TO 'new'`,
    `CREATE TYPE "public"."foo_bar_enum" AS ENUM('value1')`,
    `DROP TYPE "public"."foo_bar_enum"`,

    // safe rewrites we ourselves recommend — TypeORM never emits these, so if the
    // analyzer could not read them we would flag our own advice
    `ALTER TABLE "users" ADD CONSTRAINT "fk" FOREIGN KEY ("a") REFERENCES "b" ("id") NOT VALID`,
    `ALTER TABLE "users" ADD CONSTRAINT "users_name_null" CHECK ("name" IS NOT NULL) NOT VALID`,
    `ALTER TABLE "users" VALIDATE CONSTRAINT "users_name_null"`,
    `ALTER TABLE "users" ADD CONSTRAINT "uq" UNIQUE USING INDEX "IDX_users_name"`,

    // misc
    `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`,
    `CREATE SCHEMA IF NOT EXISTS "app"`,
    `DROP SCHEMA "app" CASCADE`,
    `CREATE DATABASE "other"`,
    `DROP DATABASE IF EXISTS "other"`,
    `CREATE SEQUENCE IF NOT EXISTS "post_id_seq" OWNED BY "post"."id"`,
    `DROP SEQUENCE "post_id_seq"`,
    `ALTER SEQUENCE "post_id_seq" OWNED BY "post"."id"`,
    `ALTER INDEX "public"."IDX_a" RENAME TO "IDX_b"`,
    `CREATE VIEW "active_users" AS SELECT * FROM "users" WHERE "active"`,
    `DROP VIEW IF EXISTS "active_users" CASCADE`,
    `TRUNCATE TABLE "post"`,
    `ALTER SCHEMA "old" RENAME TO "new"`,
]

export const MYSQL_CORPUS: string[] = [
    "CREATE TABLE `post` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB",
    "CREATE TABLE `foo` (`id` int NOT NULL AUTO_INCREMENT, `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB",
    "DROP TABLE `post`",
    "RENAME TABLE `post` TO `article`",
    "ALTER TABLE `post` ADD `title` varchar(255) NOT NULL",
    "ALTER TABLE `post` DROP COLUMN `title`",
    // MySQL always emits CHANGE, never MODIFY
    "ALTER TABLE `post` CHANGE `title` `name` varchar(255) NOT NULL",
    "ALTER TABLE `post` CHANGE `title` `title` text NOT NULL",
    "CREATE INDEX `IDX_a` ON `post` (`title`)",
    "CREATE UNIQUE INDEX `IDX_b` ON `post` (`title`)",
    "CREATE FULLTEXT INDEX `IDX_c` ON `post` (`body`) WITH PARSER ngram",
    "DROP INDEX `IDX_a` ON `post`",
    // One statement, two operations
    "ALTER TABLE `post` DROP INDEX `IDX_a`, ADD UNIQUE INDEX `IDX_b` (`title`)",
    "ALTER TABLE `account` ADD CONSTRAINT `FK_6032` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION",
    "ALTER TABLE `post` DROP FOREIGN KEY `FK_6032`",
    "ALTER TABLE `post` ADD PRIMARY KEY (`id`)",
    "ALTER TABLE `post` DROP PRIMARY KEY",
    "ALTER TABLE `post` COMMENT 'a table'",
    "TRUNCATE TABLE `post`",
    "CREATE VIEW `active_users` AS SELECT * FROM `users` WHERE `active`",
    "DROP VIEW `active_users`",
    // Hand-written forms TypeORM never generates but people do write
    "ALTER TABLE `post` ADD `x` int, ALGORITHM=COPY",
    "ALTER TABLE `post` ADD `y` int, LOCK=SHARED",
]

function unknowns(sql: string, dialect: Dialect): Operation[] {
    return analyzeSql(sql, dialect).filter((op) => op.kind === "unknown")
}

describe("analyzer corpus", () => {
    describe("postgres", () => {
        for (const sql of POSTGRES_CORPUS) {
            it(`parses ${sql.slice(0, 72)}`, () => {
                expect(unknowns(sql, "postgres")).toEqual([])
            })
        }
    })

    describe("mysql", () => {
        for (const sql of MYSQL_CORPUS) {
            it(`parses ${sql.slice(0, 72)}`, () => {
                expect(unknowns(sql, "mysql")).toEqual([])
            })
        }
    })

    it("covers every statement head TypeORM emits without a single unknown", () => {
        const all = [
            ...POSTGRES_CORPUS.flatMap((sql) => analyzeSql(sql, "postgres")),
            ...MYSQL_CORPUS.flatMap((sql) => analyzeSql(sql, "mysql")),
        ]
        const unparsed = all.filter((op) => op.kind === "unknown")
        expect(
            unparsed.map((op) => (op.kind === "unknown" ? op.sql : "")),
        ).toEqual([])
    })
})

describe("analyzer shape", () => {
    const first = (sql: string, dialect: Dialect = "postgres"): Operation => {
        const [op] = analyzeSql(sql, dialect)
        expect(op).toBeDefined()
        return op!
    }

    it("normalizes a generated ADD COLUMN into the same shape as the typed call", () => {
        const op = first(
            `ALTER TABLE "users" ADD "public_id" uuid NOT NULL DEFAULT gen_random_uuid()`,
        )
        expect(op).toMatchObject({
            kind: "addColumn",
            source: "sql",
            table: { name: "users" },
            column: {
                name: "public_id",
                nullable: false,
                type: { baseType: "uuid" },
                default: {
                    kind: "functionCall",
                    functionName: "gen_random_uuid",
                    containsCall: true,
                },
            },
        })
    })

    it("splits a multi-clause ALTER TABLE into one operation per clause", () => {
        const ops = analyzeSql(
            `ALTER TABLE "t" ADD "a" integer, ADD "b" integer, ALTER COLUMN "c" SET NOT NULL`,
            "postgres",
        )
        expect(ops.map((op) => op.kind)).toEqual([
            "addColumn",
            "addColumn",
            "changeColumnNull",
        ])
    })

    it("reads MySQL alter options and applies them to every clause", () => {
        const ops = analyzeSql(
            "ALTER TABLE `t` ADD `a` int, ALGORITHM=COPY, LOCK=SHARED",
            "mysql",
        )
        const add = ops.find((op) => op.kind === "addColumn")
        expect(add).toMatchObject({
            mysql: { algorithm: "COPY", lock: "SHARED" },
        })
    })

    it("recognizes NOT VALID, which is the form our own advice recommends", () => {
        expect(
            first(
                `ALTER TABLE "t" ADD CONSTRAINT "fk" FOREIGN KEY ("a") REFERENCES "b" ("id") NOT VALID`,
            ),
        ).toMatchObject({ kind: "createForeignKey", notValid: true })
        expect(
            first(
                `ALTER TABLE "t" ADD CONSTRAINT "c" CHECK ("x" IS NOT NULL) NOT VALID`,
            ),
        ).toMatchObject({ kind: "createCheckConstraint", notValid: true })
    })

    it("keeps a CHECK expression byte-exact, parentheses and quotes included", () => {
        const op = first(
            `ALTER TABLE "e" ADD CONSTRAINT "c" CHECK (col IN ('a','b') AND other > 0)`,
        )
        expect(op).toMatchObject({
            kind: "createCheckConstraint",
            expression: "col IN ('a','b') AND other > 0",
        })
    })

    it("treats MySQL CHANGE with a new name as a rename plus a type change", () => {
        const ops = analyzeSql(
            "ALTER TABLE `t` CHANGE `a` `b` varchar(255) NOT NULL",
            "mysql",
        )
        expect(ops.map((op) => op.kind)).toEqual([
            "renameColumn",
            "changeColumn",
        ])
    })

    it("flags an unbounded UPDATE but not a scoped one", () => {
        expect(first(`UPDATE "users" SET "active" = true`).kind).toBe(
            "backfill",
        )
        expect(
            first(`UPDATE "users" SET "active" = true WHERE id = 1`).kind,
        ).toBe("benign")
    })

    it("reports a procedural block as unparsed rather than guessing", () => {
        const op = first(`DO $$ BEGIN ALTER TABLE t DROP COLUMN c; END $$`)
        expect(op).toMatchObject({
            kind: "unknown",
            reason: "procedural-block",
        })
    })
})
